### ISSUE TITLE
Blue Screen under Windows 11

### ISSUE THREAD

**Issue by mfreeman-xtivia** [DesktopECHO/kWSL#11]
both kWSL and xWSL consistently trigger BSODs (MEMORY_MANAGEMENT) when attempting to run under Windows 11.

Installation succeeds, but very shortly after starting up and executing a few simple screen actions the BSOD is triggered. Have repeated this multiple times now

**Comment by DesktopECHO** [comment]
Are you running Windows 11 inside a VMware VM?

**Comment by mfreeman-xtivia** [comment]
No. Straight Windows 11 directly on the platform

**Comment by DesktopECHO** [comment]
Hi Mike, is your BSOD always citing MEMORY_MANAGEMENT?  Won't be able to dig into this for a while as I'm away, but I will look into it when I return home.  What build of Windows 11 are you running?
Thanks,
D.

**Comment by mfreeman-xtivia** [comment]
Yes, the BSOD reason is always "MEMORY_MANGEMENT"....

Windows 11 Pro, 22000.132. 
Windows Feature Experience Pack 1000.22000.132.0

Thanks for looking at this....

**Comment by DesktopECHO** [comment]
One other thing you can try while I'm away...
Just as an experiment, does [Kali-xRDP](https://github.com/DesktopECHO/Kali-xRDP) work?  It's based off the Kali image from the Windows Store as opposed to Ubuntu.

And one more question -- Did you happen to notice if kWSL or xWSL worked on earlier Windows 11 builds?

**Comment by mfreeman-xtivia** [comment]
I will give it a shot and let you know

**Comment by DesktopECHO** [comment]
Hi Mike,

Can you retry on Windows 11, 22000.168 and let me know if this issue persists?  
I'm not seeing a BSOD anymore, not sure if it's extremely good luck on my end or if the issue has been resolved.

Thanks,
D.

**Comment by mfreeman-xtivia** [comment]
No joy unfortunately.

Confirmed that matches my current version of Windows 11, installed kWSL, and then was able to drive around the UI for about a half dozen operations before i encountered the same BSOD (MEMORY_MANAGEMENT)

**Comment by DesktopECHO** [comment]
Thanks for checking… I got a crash as well today.  Still working on it!

**Comment by DesktopECHO** [comment]
Hi Mike, are you seeing this in build 10.0.22000.194 as well?

**Comment by mfreeman-xtivia** [comment]
I have not tried it lately. Should I?

**Comment by DesktopECHO** [comment]
The STOP error was very intermittent for me, seems to happen to you more often.  But ok so far on my Windows 11 VM...

**Comment by DesktopECHO** [comment]
One more thing... try turning off audio redirection.

**Comment by mfreeman-xtivia** [comment]
what setting controls " try turning off audio redirection"?

**Comment by DesktopECHO** [comment]
Just from the remote desktop client:
![image](https://user-images.githubusercontent.com/33142753/134956471-8ce1440f-d538-4e16-8e5f-4ea763ca8dba.png)

**Comment by crramirez** [comment]
Hello,

It happened to me with a completely unrelated action. I was doing a dnf update in Oracle Linux in WSL1. I think that WSL1 has some problems with Windows 11

Regards

**Comment by letivalo** [comment]
Hi,

I'm having this same issue, but it doesn't look like this thread's been mentioned in a while.

Laptop blue screened citing MEMORY_MANAGEMENT a few moments after connecting to the remote desktop following me running the script for the first time. I've got the latest windows 11 updates, I have WSL2 set as my default, and a reasonably beefy laptop.

Any further discoveries regarding this issue? Also on a side note, I haven't been able to connect to the remote desktop since my laptop crashed, I've just been stuck trying to run the scheduled task command and connecting to it using the icon created on my desktop. Can't connect, even though I'd been able to connect to it and bluescreen after first running the script. Am I missing something?

**Comment by DesktopECHO** [comment]
Hi, looks like the bug is fixed in recent Beta/Insider builds and should show up in the next generally-available release.  See [here](https://github.com/microsoft/WSL/issues/7480) for details.

I've seen this BSOD corrupt a running WSL instance, that's likely why you can't RDP into the Linux instance anymore. 
 Uninstall+reinstall will clear this up, but may be best to run an Insider build for now, or wait for MS to release a fix.

**Comment by DesktopECHO** [comment]
This issue has been resolved in the Windows 11 22H2 Release Preview.
